import { Product, Category, Brand } from '@/types';

export const products: Product[] = [
  {
    id: "1",
    name: "ACTRON Syrup",
    slug: "actron-syrup",
    category: "Nutritional Supplements",
    categorySlug: "nutritional-supplements",
    brand: "Glance Healthcare",
    price: 178.13,
    // originalPrice: 178,
    // discount: 31,
    description: "ACTRON Syrup is a premium nutritional supplement formulated for overall health maintenance, supporting immunity, growth, and vitality in children and adults.",
    benefits: [
      "Supports overall health and vitality",
      "Boosts immunity and infection resistance",
      "Promotes healthy growth and development",
      "Reduces fatigue and weakness",
      "Easy to consume syrup formulation"
    ],
    dosage: "As directed by physician",
    indications: ["General weakness", "Nutritional deficiency", "Post-illness recovery", "Growth support"],
    images: ["/images/medicines/Actron.jpeg"],
    rating: 4.4,
    reviews: 22,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "225ml"
  },
  {
    id: "2",
    name: "AVERION Suspension",
    slug: "averion-suspension",
    category: "Neurological Support",
    categorySlug: "neurological-support",
    brand: "Glance Healthcare",
    price: 395,
    // originalPrice: 395,
    // discount: 20,
    description: "AVERION Suspension is an advanced folate supplement formulated with Quatrefolic® (active folate) — 500 mcg per 5 mL — for superior bioavailability. Designed to support healthy brain development, red blood cell formation, nervous system health, and overall growth in children and adults. Ideal during pregnancy, lactation, and as a nutritional adjunct in folate deficiency management. \"Advanced Folate Support for Healthy Growth & Wellness\"",
    benefits: [
      "Helps support healthy brain development",
      "Supports red blood cell formation",
      "Helps maintain healthy folate levels",
      "Useful during pregnancy & lactation support",
      "Supports healthy growth in children",
      "Helps reduce nutritional folate deficiency",
      "Supports energy metabolism and overall wellness",
      "Helps in proper cell growth and repair",
      "Supports nervous system health",
      "Useful in weakness and fatigue associated with folate deficiency",
      "Helps support healthy haemoglobin formation",
      "Supports healthy fetal neural development",
      "Useful as a nutritional adjunct in anaemia management"
    ],
    composition: "Each 5 mL contains: Quatrefolic® (active folate) 500 mcg",
    dosage: "5-10 mL twice daily (BID) or as directed by physician / pediatrician",
    indications: [
      "Folate deficiency support",
      "Pregnancy nutritional supplementation",
      "Lactation nutritional support",
      "Pediatric nutritional support",
      "General weakness and fatigue",
      "Growth and development support",
      "Anaemia management (nutritional adjunct)",
      "Nervous system health"
    ],
    images: ["/images/medicines/averion.jpg"],
    rating: 4.5,
    reviews: 28,
    inStock: true,
    isPrescriptionRequired: true,
    volume: "200ml",
    flavour: "Lime & Pineapple"
  },
  {
    id: "3",
    name: "BRAIN ZEN Suspension",
    slug: "brain-zen-suspension",
    category: "Neurological Support",
    categorySlug: "neurological-support",
    brand: "Glance Healthcare",
    price: 1055,
    // originalPrice: 1055,
    // discount: 31,
    description: "BRAIN ZEN Suspension provides comprehensive neurological support with a concentrated blend of essential nutrients for brain development and cognitive function in children.",
    benefits: [
      "Supports brain development and cognitive function",
      "Improves focus, attention and learning ability",
      "Reduces behavioral challenges",
      "Supports overall neurological health",
      "Specially formulated for children"
    ],
    dosage: "As directed by pediatrician",
    indications: ["Neurological support", "Cognitive development", "Brain health", "Behavioral challenges"],
    images: ["/images/medicines/brainsusp.jpeg"],
    rating: 4.7,
    reviews: 35,
    inStock: true,
    isPrescriptionRequired: true,
    volume: "150ml"
  },
  {
    id: "4",
    name: "BRAIN ZEN Drops",
    slug: "brain-zen-drops",
    category: "Neurological Support",
    categorySlug: "neurological-support",
    brand: "Glance Healthcare",
    price:  222,
    // originalPrice: 222,
    // discount: 31,
    description: "BRAIN ZEN DROPS offers most concentrated EPA/DHA drops with appropriate ratio of required DHA (100mg) and EPA (50mg) for better brain development of newborns. Sourced from marine algae, it resembles nutrition from mother's milk.",
    benefits: [
      "Improves brain health of premature or low birth weight neonates",
      "Contains both DHA & EPA in appropriate ratio",
      "Naturally contains vitamin D and Vitamin E",
      "Complete vegetarian formula",
      "No added sugar, preservatives or artificial colors"
    ],
    composition: "Each 1ml contains: DHA 100mg, EPA 50mg, Vitamin D, Vitamin E",
    dosage: "As directed by pediatrician",
    indications: ["Premature birth", "Low birth weight", "Poor lactation", "Lactose intolerance", "Brain development support"],
    images: ["/images/medicines/brainzendrop.jpg"],
    rating: 4.8,
    reviews: 42,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "30ml"
  },
  {
    id: "5",
    name: "COGNI UP Syrup",
    slug: "cogni-up-syrup",
    category: "Neurological Support",
    categorySlug: "neurological-support",
    brand: "Glance Healthcare",
    price: 1059,
    // originalPrice: 1059,
    // discount: 31,
    description: "COGNI UP Syrup is a scientifically advanced combination of L-Carnosine, DHA, and Methylcobalamin designed to support brain development, cognitive performance, memory, and nerve health in both children and adults. Each 5 mL provides targeted neurological nutrition for enhanced mental alertness, learning ability, and nervous system support.",
    benefits: [
      "Supports brain development in children",
      "Improves memory & concentration",
      "Helps in learning ability",
      "Supports nervous system health",
      "Useful in developmental nutrition support",
      "Enhances memory & mental alertness in adults",
      "Supports cognitive performance",
      "Helps reduce mental fatigue",
      "Supports nerve health",
      "Useful in vitamin B12 deficiency support"
    ],
    composition: "Each 5 mL contains: L-Carnosine 200 mg, DHA 100 mg, Methylcobalamin 500 mcg",
    dosage: "As directed by physician/pediatrician",
    indications: [
      "Brain development support",
      "Memory & concentration",
      "Learning difficulties",
      "Nervous system health",
      "Mental fatigue",
      "Cognitive performance",
      "Vitamin B12 deficiency",
      "Developmental nutrition support"
    ],
    images: ["/images/medicines/cogniup.jpg"],
    rating: 4.3,
    reviews: 35,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "200ml"
  },
  {
    id: "6",
    name: "DIAZONE ACT Syrup",
    slug: "diazone-act-syrup",
    category: "Probiotics & Digestion",
    categorySlug: "probiotics-digestion",
    brand: "Glance Healthcare",
    price: 180,
    // originalPrice: 180,
    // discount: 28,
    description: "DIAZONE ACT Syrup is an effective anti-diarrheal formulation that helps manage acute and chronic diarrhea while maintaining gut health and restoring intestinal flora.",
    benefits: [
      "Effectively controls acute and chronic diarrhea",
      "Restores healthy intestinal flora",
      "Reduces abdominal cramps and discomfort",
      "Prevents dehydration from diarrhea",
      "Safe for children and adults"
    ],
    dosage: "As directed by physician",
    indications: ["Acute diarrhea", "Chronic diarrhea", "Traveler's diarrhea", "Antibiotic-associated diarrhea"],
    images: ["/images/medicines/DiazoneAct.jpeg"],
    rating: 4.5,
    reviews: 30,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "200ml"
  },
  {
    id: "7",
    name: "GALCIMAC D3 Syrup",
    slug: "galcimac-d3-syrup",
    category: "Vitamin Supplements",
    categorySlug: "vitamin-supplements",
    brand: "Glance Healthcare",
    price: 185,
    // originalPrice: 185,
    // discount: 31,
    description: "Calcium, Magnesium, Zinc, and Vitamin D3 syrup for strong bones, teeth, and overall health.",
    benefits: [
      "Builds and maintains strong bones and teeth",
      "Enhances calcium absorption with Vitamin D3",
      "Supports muscle relaxation and strength",
      "Boosts immune system with Zinc",
      "Prevents bone softening and fractures"
    ],
    composition: "Calcium, Magnesium, Zinc, Vitamin D3",
    dosage: "As directed by physician",
    indications: ["Calcium & Vitamin D3 deficiency", "Weak bones", "Muscle cramps", "Growing children", "Pregnancy & lactation", "Elderly bone health"],
    images: ["/images/medicines/galcimacd3.jpg"],
    rating: 4.5,
    reviews: 38,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "200ml",
    flavour: "Orange"
  },
  {
    id: "8",
    name: "GALCIMAC D3 Tablets",
    slug: "galcimac-d3-tablets",
    category: "Vitamin Supplements",
    categorySlug: "vitamin-supplements",
    brand: "Glance Healthcare",
    price:298,
    // originalPrice: 298,
    // discount: 28,
    description: "GALCIMAC D3 Tablets provide a powerful combination of Calcium, Magnesium, Zinc, and Vitamin D3 in tablet form for convenient daily supplementation.",
    benefits: [
      "Builds and maintains strong bones and teeth",
      "Enhances calcium absorption with Vitamin D3",
      "Supports muscle relaxation and strength",
      "Boosts immune system with Zinc",
      "Prevents bone softening and fractures"
    ],
    composition: "Calcium, Magnesium, Zinc, Vitamin D3",
    dosage: "As directed by physician",
    indications: ["Calcium & Vitamin D3 deficiency", "Weak bones", "Muscle cramps", "Elderly bone health", "Pregnancy & lactation"],
    images: ["/images/medicines/galcimactab.jpg"],
    rating: 4.4,
    reviews: 25,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "1*10'S"
  },
  {
    id: "9",
    name: "MINARVA ACT Syrup",
    slug: "minarva-act-syrup",
    category: "Neurological Support",
    categorySlug: "neurological-support",
    brand: "Glance Healthcare",
    price:190,
    // originalPrice: 190,
    // discount: 32,
    description: "L-Methylfolate + Methylcobalamin + Pyridoxine syrup for brain development, nerve health, and anemia.",
    benefits: [
      "Supports brain development and cognitive function",
      "Boosts nerve health and repair",
      "Improves red blood cell formation",
      "Enhances memory and concentration",
      "Replenishes Vitamin B9, B12, and B6",
      "Sugar-free formulation"
    ],
    composition: "L-Methylfolate, Methylcobalamin, Pyridoxine",
    dosage: "As directed by physician",
    indications: ["Neuropathy", "Anemia", "Vitamin B deficiency", "Poor memory", "Developmental support"],
    images: ["/images/medicines/minarva.jpg"],
    rating: 4.6,
    reviews: 29,
    inStock: true,
    isPrescriptionRequired: true,
    volume: "200ml"
  },
  {
    id: "10",
    name: "LIVERISH Syrup",
    slug: "liverish-syrup",
    category: "Nutritional Supplements",
    categorySlug: "nutritional-supplements",
    brand: "Glance Healthcare",
    price: 195,
    // originalPrice: 195,
    // discount: 31,
    description: "Super Strong Formula for liver health. Sugar-free liver tonic for liver enlargement, fatty liver, and appetite improvement.",
    benefits: [
      "Restores normal liver function",
      "Supports detoxification",
      "Improves appetite",
      "Enhances digestion and bile secretion",
      "Promotes liver regeneration",
      "Herbal and sugar-free"
    ],
    dosage: "Adults: 10-15ml twice daily, Children: 5-10ml twice daily after meals",
    indications: ["Liver enlargement", "Loss of appetite", "Fatty liver", "Indigestion", "Drug-induced liver damage"],
    images: ["/images/medicines/liverish.jpg"],
    rating: 4.3,
    reviews: 24,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "200ml"
  },
  {
    id: "11",
    name: "MELTON 9 Syrup",
    slug: "melton-9-syrup",
    category: "Sleep Support",
    categorySlug: "sleep-support",
    brand: "Glance Healthcare",
    price:270,
    // originalPrice: 270,
    // discount: 31,
    description: "MELTON 9 Syrup helps regulate the sleep-wake cycle, supports faster sleep onset, and improves overall sleep quality in children and adults.",
    benefits: [
      "Promotes natural sleep",
      "Reduces night-time restlessness",
      "Supports relaxation",
      "Reduces stress and mild anxiety",
      "Supports brain and nerve function",
      "Gentle and non-habit forming"
    ],
    dosage: "Take 30-45 minutes before bedtime as directed by physician",
    indications: ["Sleep difficulties", "Irregular sleep schedule", "Jet lag", "Night-time anxiety", "Mild insomnia"],
    images: ["/images/medicines/Melton.jpeg"],
    rating: 4.4,
    reviews: 31,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "200ml"
  },
  {
    id: "12",
    name: "ONE-A Solutions",
    slug: "one-a-solutions",
    category: "Vitamin Supplements",
    categorySlug: "vitamin-supplements",
    brand: "Glance Healthcare",
    price:275,
    // originalPrice: 275,
    // discount: 31,
    description: "Vitamin A solution for infants and children that strengthens vision, immunity, and growth.",
    benefits: [
      "Supports healthy vision & eyesight",
      "Prevents Vitamin A deficiency",
      "Improves immunity and infection resistance",
      "Supports normal growth & development",
      "Maintains healthy skin and mucous membranes"
    ],
    dosage: "0-5 Months: 1ml (50,000 IU), 6-11 months: 1ml (100,000 IU), 12 months-5 years: 2ml (200,000 IU). Repeat every 6 months",
    indications: ["Vitamin A deficiency", "Poor immunity", "Recurrent infections", "Night blindness prevention"],
    images: ["/images/medicines/onea.jpg"],
    rating: 4.7,
    reviews: 48,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "4ml"
  },
  {
    id: "13",
    name: "HistaTone Syrup",
    slug: "histatone-syrup",
    category: "Nutritional Supplements",
    categorySlug: "nutritional-supplements",
    brand: "Glance Healthcare",
    price: 550,
    // originalPrice: 550,
    // discount: 31,
    description: "Supports hemoglobin formation, prevents and treats anemia. Recommended for children with iron deficiency, adolescents and adults with low hemoglobin, and patients requiring nutritional anemia support or experiencing weakness and tiredness.",
    composition: "Iron Histidine – 30 mg / 5 mL",
    benefits: [
      "Helps increase hemoglobin levels",
      "Supports red blood cell formation",
      "Helps prevent & treat iron deficiency anemia",
      "Improves energy & reduces fatigue",
      "Supports healthy growth & development",
      "High absorption iron formulation",
      "Gentle on stomach with better tolerability",
      "Helps improve appetite & overall wellness",
      "Supports oxygen transport in the body",
      "Useful during increased iron requirement"
    ],
    dosage: "Use as directed by Physician / Pediatrician.",
    indications: [
      "Iron deficiency anemia",
      "Low hemoglobin levels",
      "Nutritional iron deficiency",
      "Weakness & fatigue",
      "Poor appetite due to anemia",
      "Growth-related iron supplementation in children",
      "Iron supplementation during recovery",
      "General nutritional support"
    ],
    images: ["/images/medicines/histatone.jpg"],
    rating: 4.4,
    reviews: 33,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "200ml"
  },
  {
    id: "14",
    name: "CARE MYO Sachets",
    slug: "care-myo-sachets",
    category: "Women Reproductive Health",
    categorySlug: "women-reproductive-health",
    brand: "Glance Healthcare",
    price:75,
    // originalPrice: 75,
    // discount: 32,
    description: "Supports female reproductive health, regulates menstrual cycles, and helps in PCOS/PCOD management.",
    benefits: [
      "Supports female reproductive health",
      "Improves ovulation and egg quality",
      "Improves insulin sensitivity",
      "Provides antioxidant protection",
      "Supports healthy sleep and hormone balance",
      "Supports healthy pregnancy preparation"
    ],
    composition: "Myo Inositol 2g, Lactoferrin, Resveratrol, D-Chiro Inositol, Melatonin 3mg, Chromium Picolinate, Vitamin D3, Folic Acid",
    dosage: "One sachet daily in lukewarm water on empty stomach or 30 minutes before meals",
    indications: ["PCOS/PCOD", "Irregular periods", "Hormonal imbalance", "Fertility support", "Preconception care"],
    images: ["/images/medicines/caremyo.jpg"],
    rating: 4.8,
    reviews: 45,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "5 GM"
  },
  {
    id: "15",
    name: "GrowArgin Granules",
    slug: "growargin-sachets",
    category: "Nutritional Supplements",
    categorySlug: "nutritional-supplements",
    brand: "Glance Healthcare",
    price: 66,
    // originalPrice: 66,
    // discount: 32,
    description: "GrowArgin Granules is a nutritional supplement formulated with L-Arginine and Proanthocyanidins to support blood circulation, energy, stamina, and overall wellness. Recommended for adults with nutritional deficiency, fatigue, weakness, or those requiring antioxidant support.",
    benefits: [
      "Helps improve blood circulation",
      "Supports energy & stamina",
      "Provides antioxidant protection",
      "Helps reduce oxidative stress",
      "Supports overall wellness & vitality",
      "L-Arginine helps nitric oxide production",
      "Supports healthy vascular function",
      "Helps improve nutrient delivery to tissues",
      "Proanthocyanidins support cellular protection",
      "Sugar-free formulation suitable for daily supplementation"
    ],
    composition: "L-Arginine, Proanthocyanidins",
    dosage: "Dissolve contents of sachet in water and use as directed by Physician.",
    indications: [
      "Nutritional supplementation",
      "Weakness & fatigue",
      "Poor blood circulation support",
      "General health & wellness support",
      "Antioxidant supplementation",
      "Increased nutritional requirements",
      "Support during recovery & stress conditions",
      "Reproductive health support"
    ],
    images: ["/images/medicines/growargin.jpeg"],
    rating: 4.3,
    reviews: 27,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "5 GM"
  },
  // {
  //   id: "16",
  //   name: "GUTSOFT Dry Syrup",
  //   slug: "gutsoft-dry-syrup",
  //   category: "Probiotics & Digestion",
  //   categorySlug: "probiotics-digestion",
  //   brand: "Glance Healthcare",
  //   price: 285,
  //   // originalPrice: 290,
  //   discount: 28,
  //   description: "GUTSOFT Dry Syrup is a comprehensive probiotic and enzyme formulation designed to restore gut flora and improve digestion. Recommended for children with digestive discomfort, poor appetite, indigestion, weak digestion, or those recovering from antibiotic use.",
  //   composition: "Bacillus Coagulans (BC30 Probiotic), Alpha Amylase, Pepsin, Lipase",
  //   benefits: [
  //     "Supports healthy digestion",
  //     "Improves absorption of nutrients",
  //     "Helps restore healthy gut flora",
  //     "Reduces bloating & gas formation",
  //     "Helps improve appetite",
  //     "Supports digestion of carbohydrates, proteins & fats",
  //     "Maintains intestinal health",
  //     "Helps in recovery after antibiotic therapy",
  //     "Promotes overall digestive comfort",
  //     "BC30 Probiotic supports immunity & gut balance",
  //     "Enzymes (Alpha Amylase, Pepsin, Lipase) help digest carbohydrates, protein, and fat"
  //   ],
  //   dosage: "Reconstitute with provided sterile water and use as directed by Physician.",
  //   indications: [
  //     "Indigestion & poor digestion",
  //     "Loss of appetite",
  //     "Bloating & abdominal discomfort",
  //     "Gas formation & stomach heaviness",
  //     "Digestive disturbances after antibiotics",
  //     "Diarrhea associated with gut flora imbalance",
  //     "Weak digestive enzyme activity in children",
  //     "Gut health maintenance"
  //   ],
  //   images: ["/images/medicines/gutsoft.jpg"],
  //   rating: 4.5,
  //   reviews: 36,
  //   inStock: true,
  //   isPrescriptionRequired: false,
  //   volume: "10G/50ML"
  // },
  {
    id: "17",
    name: "GUTSOFT Digestive Comfort Drops",
    slug: "gutsoft-drops",
    category: "Probiotics & Digestion",
    categorySlug: "probiotics-digestion",
    brand: "Glance Healthcare",
    price: 285,
    // originalPrice: 285,
    // discount: 20,
    description: "GUTSOFT Digestive Comfort Drops provide concentrated probiotic and enzyme support for infants and young children. Recommended for babies with colic, gas, bloating, poor digestion, or feeding-related discomfort.",
    composition: "Bacillus Coagulans (GBI 30 6086 – 500 Million CFU), Papain, Lactase, Amylase, Fennel Oil, Dill Oil",
    benefits: [
      "Helps reduce colic & gas in infants",
      "Supports healthy digestion",
      "Helps improve digestion of milk & food",
      "Maintains healthy gut flora",
      "Reduces bloating & abdominal discomfort",
      "Supports better nutrient absorption",
      "Helps calm tummy discomfort in babies",
      "Promotes digestive comfort & gut balance",
      "Fennel & Dill oil help soothe digestion",
      "Probiotic supports immunity & intestinal health",
      "Enzymes (Papain, Lactase, Amylase) help digest protein, lactose, and carbohydrates"
    ],
    dosage: "Use as directed by Pediatrician / Physician.",
    indications: [
      "Infant colic & stomach discomfort",
      "Gas formation & bloating in babies",
      "Indigestion & poor digestion",
      "Lactose digestion support",
      "Fussiness due to tummy discomfort",
      "Mild digestive disturbances",
      "Gut flora imbalance",
      "Feeding-related digestive discomfort"
    ],
    images: ["/images/medicines/gutsoft.jpg"],
    rating: 4.6,
    reviews: 41,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "10ml"
  },
   {
    id: "18",
    name: "GUTSOFT DRY SYRUP ",
    slug: "gutsoft-dry-drops",
    category: "Probiotics & Digestion",
    categorySlug: "probiotics-digestion",
    brand: "Glance Healthcare",
    price: 290,
    // originalPrice: 285,
    // discount: 20,
    description: "GUTSOFT Drops provide concentrated probiotic support for infants and young children, helping maintain healthy gut flora and relieve colic.",
    benefits: [
      "Concentrated probiotic support",
      "Relieves infant colic",
      "Reduces gas and bloating",
      "Restores gut microbiota",
      "Easy to administer drops"
    ],
    dosage: "Infants: 5-10 drops daily or as directed by pediatrician",
    indications: ["Infant colic", "Gas & bloating", "Gut flora imbalance", "Antibiotic-associated diarrhea"],
    images: ["/images/medicines/gutsoft2.jpeg"],
    rating: 4.6,
    reviews: 41,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "10ml"
  },
  {
    id: "19",
    name: "REUTISAFE Drops",
    slug: "reutisafe-drops",
    category: "Probiotics & Digestion",
    categorySlug: "probiotics-digestion",
    brand: "Glance Healthcare",
    price: 450,
    // originalPrice: 450,
    // discount: 20,
    description: "Recommended for Infants & Children for digestive support. Helps maintain healthy intestinal microflora.",
    benefits: [
      "Improves gut health",
      "Reduces colic and excessive crying in babies",
      "Controls gas and bloating",
      "Restores healthy gut flora",
      "Supports digestion and nutrient absorption",
      "Boosts natural immune defense"
    ],
    dosage: "Infants: 5 drops once daily or as directed by pediatrician",
    indications: ["Infant Colic", "Excessive Crying", "Gas & Bloating", "Gut Flora Imbalance", "Antibiotic Associated Diarrhea", "Weak Immunity"],
    images: ["/images/medicines/reutisafe.jpg"],
    rating: 4.9,
    reviews: 67,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "5ml"
  },
  {
    id: "20",
    name: "GLAN-C Drops",
    slug: "glan-c-drops",
    category: "Vitamin Supplements",
    categorySlug: "vitamin-supplements",
    brand: "Glance Healthcare",
    price: 130,
    // originalPrice: 130,
    // discount: 20,
    description: "GLAN-C Drops provide Vitamin C and Amino Acids to support growth, recovery, and overall wellness. Recommended for infants and children with low immunity, poor appetite, nutritional deficiency, or those in the recovery phase after illness.",
    composition: "Vitamin C 100 mg, Amino Acids",
    benefits: [
      "Helps improve immunity",
      "Supports healthy growth & development",
      "Helps improve appetite",
      "Supports energy & overall wellness",
      "Aids better nutritional support in infants & children",
      "Helps in recovery from illness & weakness",
      "Vitamin C supports antioxidant protection",
      "Helps maintain healthy skin & tissues",
      "Supports iron absorption",
      "Amino acids help support body growth & development"
    ],
    dosage: "Use as directed by Pediatrician / Physician.",
    indications: [
      "Vitamin C deficiency",
      "Low immunity in infants & children",
      "Poor appetite & weakness",
      "Growth & nutritional support",
      "Recovery after illness",
      "General weakness & fatigue",
      "Nutritional supplementation in children"
    ],
    images: ["/images/medicines/glan.jpg"],
    rating: 4.6,
    reviews: 52,
    inStock: true,
    isPrescriptionRequired: false,
    volume: "30ml"
  },
  {
    id: "21",
    name: "FOLMEC-P Syrup",
    slug: "folmec-p-syrup",
    category: "Neurological Support",
    categorySlug: "neurological-support",
    brand: "Glance Healthcare",
    price: 295,
    // originalPrice: 266,
    // discount: 28,
    description: "FOLMEC-P Syrup provides essential B-vitamins including Folic Acid, Methylcobalamin, and Pyridoxine to support nerve health, brain development, and red blood cell formation.",
    benefits: [
      "Supports nerve health and repair",
      "Promotes brain development",
      "Improves red blood cell formation",
      "Prevents neural tube defects",
      "Replenishes essential B vitamins"
    ],
    composition: "Folic Acid, Methylcobalamin, Pyridoxine",
    dosage: "As directed by physician",
    indications: ["Folate deficiency", "Neuropathy", "Anemia", "Vitamin B deficiency", "Pregnancy support"],
    images: ["/images/medicines/folmecp.jpg"],
    rating: 4.5,
    reviews: 26,
    inStock: true,
    isPrescriptionRequired: true,
    volume: "100ml"
  },
  {
    id: "22",
    name: "BRAIN ZEN Capsules",
    slug: "brain-zen-capsules",
    category: "Neurological Support",
    categorySlug: "neurological-support",
    brand: "Glance Healthcare",
    price: 545,
    // originalPrice: 545,
    // discount: 10,
    description: "BRAIN ZEN Capsules provide essential Omega-3 fatty acids (EPA & DHA) from fish oil to support brain health, memory, heart function, eye health, and overall wellness. Ideal for students, working professionals, and elderly individuals seeking cognitive and cardiovascular support.",
    composition: "Omega 3 Fish Oil – 1000 mg | EPA – 180 mg | DHA – 120 mg",
    benefits: [
      "Supports brain function & memory",
      "Helps improve focus & concentration",
      "Supports healthy heart function",
      "Helps maintain healthy cholesterol balance",
      "Supports eye & vision health",
      "DHA supports cognitive performance",
      "EPA helps support cardiovascular wellness",
      "Provides essential omega-3 fatty acids",
      "Helps reduce nutritional deficiency of omega-3",
      "Supports overall health & immunity"
    ],
    dosage: "Use as directed by Physician / Healthcare Professional",
    indications: [
      "Brain health support",
      "Memory & concentration support",
      "Heart health maintenance",
      "Eye health support",
      "Nutritional omega-3 supplementation",
      "General wellness & vitality",
      "Support during mental stress & fatigue",
      "Healthy aging support"
    ],
    images: ["/images/medicines/brainzen.jpeg"],
    rating: 4.6,
    reviews: 38,
    inStock: true,
    isPrescriptionRequired: false,
    ageGroup: "Students, Working Professionals, Adults, Elderly",
    volume: "30 Capsules"
  }
];

export const categories: Category[] = [
  { id: "1", name: "Neurological Support", slug: "neurological-support", count: products.filter(p => p.categorySlug === "neurological-support").length },
  { id: "2", name: "Probiotics & Digestion", slug: "probiotics-digestion", count: products.filter(p => p.categorySlug === "probiotics-digestion").length },
  { id: "3", name: "Vitamin Supplements", slug: "vitamin-supplements", count: products.filter(p => p.categorySlug === "vitamin-supplements").length },
  { id: "4", name: "Sleep Support", slug: "sleep-support", count: products.filter(p => p.categorySlug === "sleep-support").length },
  { id: "5", name: "Women Reproductive Health", slug: "women-reproductive-health", count: products.filter(p => p.categorySlug === "women-reproductive-health").length },
  { id: "6", name: "Nutritional Supplements", slug: "nutritional-supplements", count: products.filter(p => p.categorySlug === "nutritional-supplements").length }
];

export const brands: Brand[] = [
  { id: "1", name: "Glance Healthcare", slug: "glance-healthcare", count: products.length }
];

export function getProducts(category?: string, search?: string): Product[] {
  let filtered = [...products];
  if (category && category !== "all") {
    filtered = filtered.filter(p => p.categorySlug === category);
  }
  if (search) {
    const query = search.toLowerCase();
    filtered = filtered.filter(p =>
      p.name.toLowerCase().includes(query) ||
      p.description.toLowerCase().includes(query)
    );
  }
  return filtered;
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getRelatedProducts(categorySlug: string, currentId: string): Product[] {
  return products.filter(p => p.categorySlug === categorySlug && p.id !== currentId).slice(0, 4);
}